/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    banners: Banner;
    slides: Slide;
    products: Product;
    collections: Collection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    slides: SlidesSelect<false> | SlidesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  bytescaleKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Nombre de la categoría de producto
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., electronics, fashion)
   */
  handle: string;
  /**
   * ID de la categoría en el backend (ej. Medusa)
   */
  medusa_id?: string | null;
  /**
   * Descripción de la categoría
   */
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Parent category for hierarchical structure
   */
  parent_category?: (number | null) | Category;
  /**
   * Indica si la categoría está activa en el backend
   */
  is_active?: boolean | null;
  /**
   * Uso interno, no visible públicamente
   */
  is_internal?: boolean | null;
  /**
   * Orden de la categoría según el backend
   */
  rank?: number | null;
  /**
   * Metadatos adicionales en formato JSON
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Subcategorías hijas de esta categoría
   */
  category_children?: (number | Category)[] | null;
  /**
   * Productos asociados a esta categoría
   */
  products?: (number | Product)[] | null;
  /**
   * Fecha de creación en el backend
   */
  created_at?: string | null;
  /**
   * Fecha de actualización en el backend
   */
  updated_at?: string | null;
  /**
   * Fecha de eliminación en el backend (si aplica)
   */
  deleted_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Nombre del producto
   */
  title: string;
  /**
   * URL-friendly identifier (e.g., producto-ejemplo)
   */
  handle: string;
  /**
   * Descripción corta del producto
   */
  description?: string | null;
  /**
   * Descripción completa con formato HTML
   */
  descriptionHtml?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Marca o proveedor del producto
   */
  vendor?: string | null;
  /**
   * Tipo de producto (e.g., Electronics, Clothing)
   */
  productType?: string | null;
  status: 'active' | 'draft' | 'archived';
  /**
   * Imagen destacada del producto
   */
  featuredImage?: (number | null) | Media;
  /**
   * Galería de imágenes del producto
   */
  images?:
    | {
        image: number | Media;
        /**
         * Texto alternativo para accesibilidad
         */
        altText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Categorías a las que pertenece el producto
   */
  categories?: (number | Category)[] | null;
  /**
   * Etiquetas para búsqueda y filtrado
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opciones del producto (Color, Talla, etc.)
   */
  options?:
    | {
        /**
         * Nombre de la opción (e.g., Color, Talla)
         */
        name?: string | null;
        /**
         * Valores posibles para esta opción
         */
        values?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Variantes del producto (diferentes colores, tallas, etc.)
   */
  variants?:
    | {
        /**
         * Título de la variante (e.g., "Rojo / Grande")
         */
        title?: string | null;
        /**
         * SKU único de la variante
         */
        sku?: string | null;
        /**
         * Precio de la variante
         */
        price?: number | null;
        /**
         * Precio de comparación (precio original)
         */
        compareAtPrice?: number | null;
        currencyCode: 'USD' | 'EUR' | 'MXN' | 'COP';
        /**
         * Opciones seleccionadas para esta variante
         */
        selectedOptions?:
          | {
              name: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Cantidad disponible en inventario
         */
        quantityAvailable?: number | null;
        /**
         * Disponible para venta
         */
        availableForSale?: boolean | null;
        /**
         * Imagen específica de esta variante
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Rango de precios del producto (calculado automáticamente desde las variantes)
   */
  priceRange?: {
    /**
     * Precio mínimo entre todas las variantes (calculado automáticamente)
     */
    minPrice?: number | null;
    /**
     * Precio máximo entre todas las variantes (calculado automáticamente)
     */
    maxPrice?: number | null;
    currencyCode?: ('USD' | 'EUR' | 'MXN' | 'COP') | null;
  };
  /**
   * Precio mínimo del producto (calculado automáticamente)
   */
  minPrice?: number | null;
  inventory?: {
    /**
     * Cantidad total en inventario
     */
    totalQuantity?: number | null;
    /**
     * Rastrear cantidad en inventario
     */
    trackQuantity?: boolean | null;
  };
  seo?: {
    /**
     * Título para SEO (máx. 60 caracteres)
     */
    metaTitle?: string | null;
    /**
     * Descripción para SEO (máx. 160 caracteres)
     */
    metaDescription?: string | null;
  };
  /**
   * Metadatos personalizados del producto
   */
  productDetailsMetafield?: {
    /**
     * Metadatos adicionales en formato JSON
     */
    value?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Fecha de publicación
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  title: string;
  subtitle?: string | null;
  image: number | Media;
  /**
   * Optional separate image for mobile devices
   */
  mobileImage?: (number | null) | Media;
  link: {
    url: string;
    label: string;
    openInNewTab?: boolean | null;
  };
  position: 'hero' | 'secondary' | 'sidebar';
  active?: boolean | null;
  /**
   * Lower numbers appear first
   */
  displayOrder?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides".
 */
export interface Slide {
  id: number;
  title: string;
  context?: string | null;
  /**
   * Categoría seleccionada para este slide
   */
  action_boton?: (number | null) | Category;
  /**
   * Imagen del slide
   */
  img_url: number | Media;
  /**
   * ID del producto estrella de Medusa
   */
  product_star?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  /**
   * Título de la colección de productos
   */
  title: string;
  /**
   * Identificador amigable para URL (e.g., summer-2024)
   */
  handle: string;
  /**
   * Imagen de la colección
   */
  img_url?: (number | null) | Media;
  /**
   * Metadatos adicionales en formato JSON
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Productos que pertenecen a esta colección
   */
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'slides';
        value: number | Slide;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  bytescaleKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  handle?: T;
  medusa_id?: T;
  description?: T;
  image?: T;
  parent_category?: T;
  is_active?: T;
  is_internal?: T;
  rank?: T;
  metadata?: T;
  category_children?: T;
  products?: T;
  created_at?: T;
  updated_at?: T;
  deleted_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  image?: T;
  mobileImage?: T;
  link?:
    | T
    | {
        url?: T;
        label?: T;
        openInNewTab?: T;
      };
  position?: T;
  active?: T;
  displayOrder?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides_select".
 */
export interface SlidesSelect<T extends boolean = true> {
  title?: T;
  context?: T;
  action_boton?: T;
  img_url?: T;
  product_star?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  description?: T;
  descriptionHtml?: T;
  vendor?: T;
  productType?: T;
  status?: T;
  featuredImage?: T;
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        id?: T;
      };
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  options?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        title?: T;
        sku?: T;
        price?: T;
        compareAtPrice?: T;
        currencyCode?: T;
        selectedOptions?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
        quantityAvailable?: T;
        availableForSale?: T;
        image?: T;
        id?: T;
      };
  priceRange?:
    | T
    | {
        minPrice?: T;
        maxPrice?: T;
        currencyCode?: T;
      };
  minPrice?: T;
  inventory?:
    | T
    | {
        totalQuantity?: T;
        trackQuantity?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  productDetailsMetafield?:
    | T
    | {
        value?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  img_url?: T;
  metadata?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}